# vim:ft=kitty

## name: EarthTone Cocoa Dark
## author: you + vibes
## license: MIT
## blurb: duotone theme | warm cocoa brown - sand stone


#: The basic colors

foreground #E7EDF0
background #000000
selection_foreground #2F170F
selection_background #8A6E60


#: Cursor colors

cursor #E7EDF0
cursor_text_color #2F170F


#: URL underline color when hovering with mouse

url_color #846C62


#: kitty window border colors and terminal bell colors

active_border_color #8A6E60
inactive_border_color #2F170F
bell_border_color #754E3B
visual_bell_color none


#: OS Window titlebar colors

wayland_titlebar_color #754E3B
macos_titlebar_color #754E3B


#: Tab bar colors

active_tab_foreground #E7EDF0
active_tab_background #2F170F
inactive_tab_foreground #846C62
inactive_tab_background #754E3B
tab_bar_background #754E3B
tab_bar_margin_color none


#: Colors for marks (marked text in the terminal)

mark1_foreground #2F170F
mark1_background #8A6E60
mark2_foreground #2F170F
mark2_background #846C62
mark3_foreground #2F170F
mark3_background #754E3B


#: The basic 16 colors

#: black
color0  #2F170F
color8  #754E3B

#: red
color1  #754E3B
color9  #8A6E60

#: green
color2  #8A6E60
color10 #846C62

#: yellow
color3  #E7EDF0
color11 #8A6E60

#: blue
color4  #846C62
color12 #8A6E60

#: magenta
color5  #754E3B
color13 #846C62

#: cyan
color6  #8A6E60
color14 #E7EDF0

#: white
color7  #E7EDF0
color15 #E7EDF0

