bar {
	swaybar_command waybar
}

exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f -c 000000'


exec /usr/lib/polkit-kde-authentication-agent-1
exec sleep 1 && /usr/bin/amneziavpn
exec dunst
exec keepassxc
exec sleep 5 && nextcloud


exec $HOME/.config/custom_scripts/autostart.sh
