bar {
	swaybar_command waybar
}

exec swayidle -w \
         timeout 300 'swaylock -f -c 000000' \
         timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f -c 000000'


exec /usr/lib/polkit-kde-authentication-agent-1
exec dbus-update-activation-environment --systemd --all
exec dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=sway
exec "systemctl --user import-environment {,WAYLAND_}DISPLAY SWAYSOCK; systemctl --user start sway-session.target"
exec swaymsg -t subscribe '["shutdown"]' && systemctl --user stop sway-session.target
exec sleep 1 && AmneziaVPN
exec dunst
exec keepassxc
exec udiskie
exec sleep 5 && nextcloud


exec $HOME/.config/custom_scripts/autostart.sh
